### ISSUE TITLE
Receiving error while running Demo.ipynb

### ISSUE THREAD

**Issue by arihantparsoya** [LokiTechnologies/EqualAreaCartogram#14]
![screenshot 2019-02-05 at 8 14 29 pm](https://user-images.githubusercontent.com/15258498/52280859-d0f95800-2982-11e9-9774-a92d6deef2c2.png)

**Comment by rishsriv** [comment]
Have you created a directory named `sample_output`?

Will fix this by improving error handling from my end – but creating the directory should fix this.

**Comment by rishsriv** [comment]
Fixed in the latest push. Thanks for reporting!
