### ISSUE TITLE
R Implementation

### ISSUE THREAD

**Issue by sassalley** [LokiTechnologies/EqualAreaCartogram#7]
Hi @rishsriv great implementation! Really glad that there's a python version now. Just wanted to let you know that the R implementation does work with non-contiguous spaces. I believe there's an example here: http://rpubs.com/Hailstone/326118 

Best,

sassalley

**Comment by rishsriv** [comment]
Ah got it! My bad for not realizing that. Just fixed the `README.md` file. Apologies :-)
